import React, { useState, useEffect } from 'react'; // Added useEffect
import { useScheduler } from '../context/SchedulerContext';
import { ScheduledClass } from '../types';
import { set, addHours, setDay as dfnsSetDay, getDay as dfnsGetDay, format as dfnsFormat, parseISO } from 'date-fns'; // Added getDay, format, parseISO

const DAYS_OF_WEEK_OPTIONS = [
  { value: 1, label: 'Monday' }, { value: 2, label: 'Tuesday' }, { value: 3, label: 'Wednesday' },
  { value: 4, label: 'Thursday' }, { value: 5, label: 'Friday' }, { value: 6, label: 'Saturday' },
  { value: 0, label: 'Sunday' },
];

const TIME_SLOTS_OPTIONS = Array.from({ length: 13 }, (_, i) => {
  const hour = i + 8;
  return `${String(hour).padStart(2, '0')}:00`;
});

interface ScheduleFormProps {
  editingClass: ScheduledClass | null;
  onFormClose: () => void; // To close the form or reset editing state
}

const ScheduleForm: React.FC<ScheduleFormProps> = ({ editingClass, onFormClose }) => {
  const { teachers, groups, addScheduledClass, updateScheduledClass } = useScheduler();

  const [selectedTeacherId, setSelectedTeacherId] = useState<string>('');
  const [selectedGroupId, setSelectedGroupId] = useState<string>('');
  const [selectedDay, setSelectedDay] = useState<number>(1); // Default Monday
  const [selectedTime, setSelectedTime] = useState<string>(TIME_SLOTS_OPTIONS[0]); // Default 08:00

  const isEditMode = !!editingClass;

  useEffect(() => {
    if (editingClass) {
      const startTime = typeof editingClass.startTime === 'string' ? parseISO(editingClass.startTime) : editingClass.startTime;

      setSelectedTeacherId(editingClass.teacherId);
      setSelectedGroupId(editingClass.groupId);
      // date-fns getDay(): Sunday is 0, Monday is 1. This matches our DAYS_OF_WEEK_OPTIONS values.
      setSelectedDay(dfnsGetDay(startTime));
      setSelectedTime(dfnsFormat(startTime, 'HH:mm'));
    } else {
      // Reset form when not in edit mode or editingClass is cleared
      setSelectedTeacherId('');
      setSelectedGroupId('');
      setSelectedDay(1); // Default Monday
      setSelectedTime(TIME_SLOTS_OPTIONS[0]); // Default 08:00
    }
  }, [editingClass]);

  const handleSubmit = (event: React.FormEvent) => {
    event.preventDefault();
    if (!selectedTeacherId || !selectedGroupId) {
      alert('Please select a teacher and a group.');
      return;
    }

    let baseDate = new Date(); // Base for creating new date
    if (isEditMode && editingClass) {
        // Preserve original date when editing, only change day/time if they are different
        baseDate = typeof editingClass.startTime === 'string' ? parseISO(editingClass.startTime) : editingClass.startTime;
    }

    let newStartTime = dfnsSetDay(baseDate, selectedDay, { weekStartsOn: 1 });
    const [hour, minute] = selectedTime.split(':').map(Number);
    newStartTime = set(newStartTime, { hours: hour, minutes: minute, seconds: 0, milliseconds: 0 });
    const newEndTime = addHours(newStartTime, 1);

    if (isEditMode && editingClass) {
      const updatedClassData: ScheduledClass = {
        ...editingClass,
        teacherId: selectedTeacherId,
        groupId: selectedGroupId,
        startTime: newStartTime,
        endTime: newEndTime,
      };
      updateScheduledClass(updatedClassData);
    } else {
      // For new class, ID is generated by addScheduledClass in context
      const newClassData: Omit<ScheduledClass, 'id'> = {
        teacherId: selectedTeacherId,
        groupId: selectedGroupId,
        startTime: newStartTime,
        endTime: newEndTime,
      };
      // Cast to any if addScheduledClass signature needs full ScheduledClass but handles ID itself
      addScheduledClass(newClassData as any);
    }
    onFormClose(); // Close form/reset editing state after submission
  };

  const formStyle: React.CSSProperties = { /* ... same styles ... */
    padding: '20px', border: '1px solid #ccc', borderRadius: '8px', marginBottom: '20px',
    display: 'flex', flexDirection: 'column', gap: '15px', maxWidth: '400px',
  };
  const selectStyle: React.CSSProperties = { /* ... same styles ... */
    padding: '10px', borderRadius: '4px', border: '1px solid #ddd', width: '100%'
  };
  const buttonStyle: React.CSSProperties = { /* ... same styles ... */
    padding: '10px 15px', borderRadius: '4px', border: 'none',
    backgroundColor: '#007bff', color: 'white', cursor: 'pointer', fontSize: '1em',
  };
   const cancelButtonStyle: React.CSSProperties = {
    ...buttonStyle,
    backgroundColor: '#6c757d', // A grey color for cancel
    marginTop: '10px',
  };


  return (
    <form onSubmit={handleSubmit} style={formStyle}>
      <h3>{isEditMode ? 'Edit Class' : 'Create New Class'}</h3>
      <div>
        <label htmlFor="teacher-select" style={{display: 'block', marginBottom: '5px'}}>Teacher:</label>
        <select id="teacher-select" value={selectedTeacherId} onChange={e => setSelectedTeacherId(e.target.value)} required style={selectStyle}>
          <option value="" disabled={isEditMode}>Select Teacher</option>
          {teachers.map(teacher => <option key={teacher.id} value={teacher.id}>{teacher.name}</option>)}
        </select>
      </div>
      <div>
        <label htmlFor="group-select" style={{display: 'block', marginBottom: '5px'}}>Group:</label>
        <select id="group-select" value={selectedGroupId} onChange={e => setSelectedGroupId(e.target.value)} required style={selectStyle}>
          <option value="" disabled={isEditMode}>Select Group</option>
          {groups.map(group => <option key={group.id} value={group.id}>{group.name}</option>)}
        </select>
      </div>
      <div>
        <label htmlFor="day-select" style={{display: 'block', marginBottom: '5px'}}>Day of the Week:</label>
        <select id="day-select" value={selectedDay} onChange={e => setSelectedDay(parseInt(e.target.value, 10))} required style={selectStyle}>
          {DAYS_OF_WEEK_OPTIONS.map(day => <option key={day.value} value={day.value}>{day.label}</option>)}
        </select>
      </div>
      <div>
        <label htmlFor="time-select" style={{display: 'block', marginBottom: '5px'}}>Time:</label>
        <select id="time-select" value={selectedTime} onChange={e => setSelectedTime(e.target.value)} required style={selectStyle}>
          {TIME_SLOTS_OPTIONS.map(time => <option key={time} value={time}>{time}</option>)}
        </select>
      </div>
      <button type="submit" style={buttonStyle}>{isEditMode ? 'Update Class' : 'Create Class'}</button>
      {isEditMode && (
        <button type="button" onClick={onFormClose} style={cancelButtonStyle}>
          Cancel Edit
        </button>
      )}
    </form>
  );
};

export default ScheduleForm;
